// Hyderabad-only "Evaluation Report" — the final document generated by the
// Generate Evaluation Report wizard (src/app/admin/leads/evaluation-report-wizard.tsx).
// Structurally modeled on renderHyderabadAgreement() in indiaAgreementTemplate.ts
// (same COMPANY branding block, same esc()/box() helpers, same print CSS) since
// that's the visual standard for a Hyderabad-branded printed document — but this
// is an assessment report, not a signed agreement, so the branding block and
// print CSS are duplicated locally rather than imported from that file.

const esc = (value: unknown) => String(value ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const COMPANY = {
  nameEn: 'Didactic Migration Consultants Pvt Ltd - Hyderabad Branch',
  tradingAs: 'Trading as "DM Consultants" / "DMC Immigration"',
  addressEn: '2nd Floor, UMA Plaza, Nagarjuna Circle Road, Beside Mahindra Showroom, Mothi Nagar, Nagarjuna Hills, Punjagutta, Hyderabad, Telangana 500082, India',
  phone: '+91 40 4006 1682',
  email: 'hyderabad@dm-consultant.in',
};

export interface EvaluationReportValues {
  reportDate: string;
  clientName: string;
  clientAddress: string;
  clientPhoneEmail: string;
  destinationCountry: string;
  programOfInterest: string;
  eligibilitySummary: string;
  feePaid: string;
  discountApplied: string;
  netPayable: string;
  receiptNumber?: string;
  generatedBy?: string;
}

const textOrBlank = (value: unknown, fallback = '________________') => {
  const result = String(value ?? '').trim();
  return result || fallback;
};

const box = (title: string, body: string, className = '') => `<section class="report-box ${className}">
  ${title ? `<h2>${esc(title)}</h2>` : ''}
  <p>${esc(body)}</p>
</section>`;

export function renderEvaluationReportHtml(v: EvaluationReportValues): string {
  const reportDate = textOrBlank(v.reportDate);
  const clientName = textOrBlank(v.clientName);
  const clientAddress = textOrBlank(v.clientAddress);
  const clientPhoneEmail = textOrBlank(v.clientPhoneEmail);
  const destinationCountry = textOrBlank(v.destinationCountry);
  const programOfInterest = textOrBlank(v.programOfInterest);
  const eligibilitySummary = textOrBlank(v.eligibilitySummary, 'No eligibility summary was recorded.');
  const receiptNumber = textOrBlank(v.receiptNumber, 'N/A');
  const generatedBy = textOrBlank(v.generatedBy);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Evaluation Report - ${esc(clientName)}</title>
  <style>
    @page {
      size: Letter;
      margin: 9mm 6mm 13mm;
    }

    * { box-sizing: border-box; }

    html, body {
      margin: 0;
      padding: 0;
      background: #ffffff;
      color: #111111;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 11px;
      line-height: 1.5;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .document {
      width: 100%;
      max-width: 8.5in;
      margin: 0 auto;
      padding: 0;
    }

    .report-header {
      background: #ffffff;
      color: #111111;
      border: 1.5px solid #4b5563;
      padding: 12px 14px;
      margin: 0 0 10px;
      break-inside: avoid;
      page-break-inside: avoid;
    }

    .company-name {
      font-weight: 700;
      font-size: 13px;
    }

    .trading-as,
    .company-address,
    .company-contact {
      font-size: 9.5px;
      color: #4b5563;
      margin-top: 2px;
    }

    .report-name {
      margin-top: 8px;
      font-weight: 700;
      text-transform: uppercase;
      font-size: 15px;
      letter-spacing: .3px;
    }

    .report-box {
      border: 1.5px solid #4b5563;
      overflow: hidden;
      margin: 0 0 8px;
      break-inside: avoid;
      page-break-inside: avoid;
      background: #ffffff;
      padding: 9px 12px;
    }

    .report-box h2 {
      margin: 0 0 6px;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: .3px;
      color: #111827;
      border-bottom: 1.5px solid #4b5563;
      padding-bottom: 4px;
    }

    .report-box p {
      margin: 0;
      white-space: pre-line;
    }

    .disclaimer {
      background: #fff7ed;
      border-color: #b91c1c;
    }

    .disclaimer h2 {
      color: #b91c1c;
      border-bottom-color: #b91c1c;
    }

    .signature-box {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
    }

    .signature-box .report-box {
      margin-bottom: 0;
    }

    .print-footer {
      position: fixed;
      left: 6mm;
      right: 6mm;
      bottom: 4mm;
      display: flex;
      justify-content: center;
      color: #444;
      font-size: 8.4px;
      line-height: 1;
      text-align: center;
      white-space: nowrap;
    }

    .page-number::after {
      content: counter(page);
    }

    @media screen {
      body {
        background: #eef0f3;
        padding: 14px 0;
      }

      .document {
        background: #fff;
        min-height: 11in;
        padding: 9mm 6mm 13mm;
        box-shadow: 0 2px 12px rgba(0, 0, 0, .1);
      }

      .print-footer {
        position: static;
        margin-top: 11px;
      }
    }

    @media print {
      .document { padding: 0; }
      .print-footer { position: fixed; }
    }

    @media (max-width: 700px) {
      html, body { font-size: 11px; }
      .document { width: 100%; }
      .signature-box { grid-template-columns: 1fr; }
      .print-footer { white-space: normal; }
    }
  </style>
</head>
<body>
  <main class="document">
    <header class="report-header">
      <div class="company-name">${esc(COMPANY.nameEn)}</div>
      <div class="trading-as">${esc(COMPANY.tradingAs)}</div>
      <div class="company-address">${esc(COMPANY.addressEn)}</div>
      <div class="company-contact">Phone: ${esc(COMPANY.phone)} | Email: ${esc(COMPANY.email)}</div>
      <div class="report-name">Evaluation Report</div>
    </header>

    ${box('REPORT DETAILS', `Report Date ${reportDate}\nReceipt No. ${receiptNumber}`)}

    ${box('CLIENT DETAILS', `Client Name ${clientName}\nClient Address ${clientAddress}\nPhone / Email ${clientPhoneEmail}`)}

    ${box('PROGRAM & DESTINATION OF INTEREST', `Destination Country/ies ${destinationCountry}\nProgram / Service of Interest ${programOfInterest}`)}

    ${box('ELIGIBILITY ASSESSMENT', eligibilitySummary)}

    ${box('FEE DETAILS', `Evaluation Fee (INR) ${textOrBlank(v.feePaid, '1,500.00')}\nDiscount Applied (INR) ${textOrBlank(v.discountApplied, '0.00')}\nNet Amount Paid (INR) ${textOrBlank(v.netPayable, '1,500.00')}`)}

    ${box(
      'DISCLAIMER',
      'This Evaluation Report is an assessment only, prepared on the basis of the information and documents provided by the Client at the time of this evaluation, and does not constitute a promise, warranty, or guarantee of any visa, immigration, admission, or other outcome. Final decisions on any application rest solely with the relevant government/visa authority. This report does not itself authorize the commencement of any paid service beyond the evaluation covered by this document.',
      'disclaimer',
    )}

    <div class="signature-box">
      ${box('EVALUATED BY', `Name ${generatedBy}\nDM Consultants - Hyderabad Branch\nDate ${reportDate}`)}
      ${box('FOR THE CLIENT', `Signature ________________________________\nName ${clientName}\nDate ________________________________`)}
    </div>

    <footer class="print-footer">
      ${COMPANY.nameEn} - Evaluation Report - Page <span class="page-number"></span>
    </footer>
  </main>
</body>
</html>`;
}

export function printEvaluationReport(v: EvaluationReportValues): boolean {
  const html = renderEvaluationReportHtml(v);
  const win = window.open('', '_blank', 'width=900,height=1100');
  if (!win) {
    window.toast.warning('Allow pop-ups to view the evaluation report.');
    return false;
  }
  win.document.write(html);
  win.document.close();
  win.addEventListener('load', () => setTimeout(() => win.print(), 300));
  if (win.document.readyState === 'complete') setTimeout(() => win.print(), 500);
  return true;
}
