import { NextRequest, NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import { resolveGeneratedDocumentPath, verifyStorageKeySignature } from '@/services/document-service';

type RouteContext = { params: Promise<{ path?: string[] }> };

// Each segment is generated by DocumentService itself (a fixed doc-type union plus a
// filename already sanitized to this same charset) - reject anything else outright rather
// than trying to resolve-and-compare paths for traversal safety.
const isSafeSegment = (segment: string) => /^[a-zA-Z0-9._-]+$/.test(segment);

export async function GET(request: NextRequest, context: RouteContext) {
  const { path: segments } = await context.params;

  if (!segments || segments.length === 0 || !segments.every(isSafeSegment)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const storageKey = segments.join('/');
  const expires = Number(request.nextUrl.searchParams.get('expires'));
  const signature = request.nextUrl.searchParams.get('signature') || '';

  if (!verifyStorageKeySignature(storageKey, expires, signature)) {
    return NextResponse.json({ error: 'This link is invalid or has expired' }, { status: 403 });
  }

  try {
    const file = await readFile(resolveGeneratedDocumentPath(storageKey));
    return new NextResponse(new Uint8Array(file), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="${segments[segments.length - 1]}"`,
        'Cache-Control': 'private, max-age=0, no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
}
