export interface Lead {
  id: number;
  fname: string;
  mname: string;
  lname: string;
  email: string;
  phone: string;
  mobile: string;
  whatsapp_number?: string | null;
  nationality: string;
  address: string;
  dob: string;
  gender: string;
  id_number: string;
  id_expiry: string;
  country_interest: string;
  country_interest_label?: string;
  service_interest: string;
  service_interest_label?: string;
  market_source: string;
  market_source_label?: string;
  appointment: string;
  followup: string;
  folowuptime: string;
  followupstat: number;
  enquiry: string;
  convet: string;
  priority: string;
  status: string;
  regdate: string;
  assignTo: number;
  branch: number;
  region: number;
  payTotal: number;
  paidYet: number;
  payBalance: number;
  lead_remark: string;
  created: string;
  lead_quality: string;
  campaign?: string;
  latest_remark?: string;
  agreementNumber?: string;
  dmEmployeeByASSIGNTo?: { id: number; name: string };
  dmEmployeeByCoUNSILOR?: { id: number; name: string };
  dmBranch?: {
    id: number;
    name: string;
    nameAr?: string | null;
    address?: string | null;
    email?: string | null;
    mobile?: string | null;
    licenseNumber?: string | null;
    vatGstPercent?: number | string | null;
    abbrv?: string | null;
  };
}
